MCP4725: Remove erroneous const keyword from parameter
Previously, when MCP4725_EXTENDED was defined, compilation of the library failed:

E:\arduino\libraries\MCP4725\MCP4725.cpp: In member function 'int MCP4725::writeRegisterMode(uint16_t, uint8_t)':

E:\arduino\libraries\MCP4725\MCP4725.cpp:195:9: error: assignment of read-only parameter 'reg'

     reg = reg | (_powerDownMode << 1);

         ^